name: node

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  project:
    uses: ./.github/workflows/ci-frontend.yml
    with:
      workdir: "tests/node/"
