name: rust-tauri

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  project:
    uses: ./.github/workflows/ci-rust-tauri.yml
    permissions:
      contents: read
    with:
      workdir: "tests/node/"
      release: false
